//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub calendar_id: i32,
    pub title: String,
    pub description: Option<String>,
    pub location: Option<String>,
    pub event_colour: String,
    pub start_time: DateTime,
    pub end_time: DateTime,
    pub time_zone: Option<String>,
    pub event_created_at: DateTime,
    pub event_updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::calendar::Entity",
        from = "Column::CalendarId",
        to = "super::calendar::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Calendar,
}

impl Related<super::calendar::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Calendar.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
