//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub event_id: i32,
    pub calendar_id: i32,
    pub event_title: String,
    pub event_description: Option<String>,
    pub event_location: Option<String>,
    pub event_colour: String,
    pub event_start_time: DateTime,
    pub event_end_time: DateTime,
    pub event_created_at: DateTimeWithTimeZone,
    pub event_updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation, Serialize)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::calendar::Entity",
        from = "Column::CalendarId",
        to = "super::calendar::Column::CalendarId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Calendar,
}

impl Related<super::calendar::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Calendar.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
