//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub user_id: i32,
    pub user_name: String,
    #[sea_orm(unique)]
    pub user_username: String,
    #[sea_orm(unique)]
    pub user_mobile: String,
    #[sea_orm(unique)]
    pub user_email: String,
    pub user_password: String,
    pub user_verified: bool,
    pub user_created_at: DateTimeWithTimeZone,
    pub user_updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation, Serialize)]
pub enum Relation {
    #[sea_orm(has_many = "super::calendar::Entity")]
    Calendar,
}

impl Related<super::calendar::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Calendar.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
